# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  matrix:
    - LUA=lua5.1                LUAVER=5.1
    - LUA=lua5.2                LUAVER=5.2
    - LUA=luajit                LUAVER=5.1

# Tool setup.
install:
  - sudo apt-get install lua5.1
  - sudo apt-get install lua5.2
  - sudo apt-get install luajit

# Build and test.
script:
  - make LUA="$LUA" test
